# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GBIF_USER: ${{ secrets.GBIF_USER }}
      GBIF_PWD: ${{ secrets.GBIF_PWD }}
      GBIF_EMAIL: ${{ secrets.GBIF_EMAIL }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # ADD THIS: Install system dependencies for spatial packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            libnetcdf-dev \
            libsqlite3-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: coverage

      - name: Setup
        run: |
          R CMD INSTALL .

      - name: Install packages
        run: |
            Rscript -e "install.packages('covr')"

      - name: Install rnaturalearthhires
        run: |
          Rscript -e "install.packages('rnaturalearthhires', repos = 'https://ropensci.r-universe.dev')"

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            token = Sys.getenv("CODECOV_TOKEN")
          )
        shell: Rscript {0}

      - name: Debug test failure
        if: failure()
        run: |
          echo "=== R Session Info ==="
          R -e "sessionInfo()"
          echo "=== Test Output Files ==="
          find /tmp -name "*.Rout.fail" -exec echo "File: {}" \; -exec cat {} \; 2>/dev/null || echo "No .Rout.fail files found"
          echo "=== Test Directory ==="
          ls -la tests/testthat/ || echo "No tests/testthat directory"
