- name: Test coverage
  run: |
    covr::codecov(
    token = Sys.getenv("CODECOV_TOKEN"),
    quiet = FALSE,
    clean = FALSE,
    install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
    )
  shell: Rscript {0}
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
